/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as NamazRouteImport } from './routes/namaz'
import { Route as HamdNaatRouteImport } from './routes/hamd-naat'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DeenBuddyRouteImport } from './routes/deen-buddy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as ApiDeenChatRouteImport } from './routes/api/deen-chat'

const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const NamazRoute = NamazRouteImport.update({
  id: '/namaz',
  path: '/namaz',
  getParentRoute: () => rootRouteImport,
} as any)
const HamdNaatRoute = HamdNaatRouteImport.update({
  id: '/hamd-naat',
  path: '/hamd-naat',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DeenBuddyRoute = DeenBuddyRouteImport.update({
  id: '/deen-buddy',
  path: '/deen-buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeenChatRoute = ApiDeenChatRouteImport.update({
  id: '/api/deen-chat',
  path: '/api/deen-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deen-buddy': typeof DeenBuddyRoute
  '/favorites': typeof FavoritesRoute
  '/hamd-naat': typeof HamdNaatRoute
  '/namaz': typeof NamazRoute
  '/tasbih': typeof TasbihRoute
  '/api/deen-chat': typeof ApiDeenChatRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deen-buddy': typeof DeenBuddyRoute
  '/favorites': typeof FavoritesRoute
  '/hamd-naat': typeof HamdNaatRoute
  '/namaz': typeof NamazRoute
  '/tasbih': typeof TasbihRoute
  '/api/deen-chat': typeof ApiDeenChatRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deen-buddy': typeof DeenBuddyRoute
  '/favorites': typeof FavoritesRoute
  '/hamd-naat': typeof HamdNaatRoute
  '/namaz': typeof NamazRoute
  '/tasbih': typeof TasbihRoute
  '/api/deen-chat': typeof ApiDeenChatRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/deen-buddy'
    | '/favorites'
    | '/hamd-naat'
    | '/namaz'
    | '/tasbih'
    | '/api/deen-chat'
    | '/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/deen-buddy'
    | '/favorites'
    | '/hamd-naat'
    | '/namaz'
    | '/tasbih'
    | '/api/deen-chat'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/deen-buddy'
    | '/favorites'
    | '/hamd-naat'
    | '/namaz'
    | '/tasbih'
    | '/api/deen-chat'
    | '/settings/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DeenBuddyRoute: typeof DeenBuddyRoute
  FavoritesRoute: typeof FavoritesRoute
  HamdNaatRoute: typeof HamdNaatRoute
  NamazRoute: typeof NamazRoute
  TasbihRoute: typeof TasbihRoute
  ApiDeenChatRoute: typeof ApiDeenChatRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namaz': {
      id: '/namaz'
      path: '/namaz'
      fullPath: '/namaz'
      preLoaderRoute: typeof NamazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hamd-naat': {
      id: '/hamd-naat'
      path: '/hamd-naat'
      fullPath: '/hamd-naat'
      preLoaderRoute: typeof HamdNaatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deen-buddy': {
      id: '/deen-buddy'
      path: '/deen-buddy'
      fullPath: '/deen-buddy'
      preLoaderRoute: typeof DeenBuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deen-chat': {
      id: '/api/deen-chat'
      path: '/api/deen-chat'
      fullPath: '/api/deen-chat'
      preLoaderRoute: typeof ApiDeenChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DeenBuddyRoute: DeenBuddyRoute,
  FavoritesRoute: FavoritesRoute,
  HamdNaatRoute: HamdNaatRoute,
  NamazRoute: NamazRoute,
  TasbihRoute: TasbihRoute,
  ApiDeenChatRoute: ApiDeenChatRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
